data_configs:
  dataset_class: 'SimDatasetWithCovariates'

network_configs:
  model_name: 'dnnCGM'
  num_nodes: 90
  num_covariates: 10
  beta_hidden_dims: 128
  beta_dropout: 0.3

opt_configs:
  learning_rate: 0.0005
  scheduler_type: 'StepLR'
  step_size: 20
  gamma: 0.25
  
train_configs:
  max_epochs: 50
  gradient_clip_val: 1.0
  batch_size: 512
  verbose: 10
  es_patience: null
  es_monitor: 'val_loss'
  num_val: 1000
  num_test: 1000

